const fs = require('fs');

// Fix blog.html
let blogHtml = fs.readFileSync('blog.html', 'utf8');
blogHtml = blogHtml.replace(/<div class="byline".*?>.*?<\/div>\s*/g, '');
// Also fix the modal byline in blog.html
blogHtml = blogHtml.replace(/<div id="blogModalByline".*?>.*?<\/div>\s*/g, '');
fs.writeFileSync('blog.html', blogHtml);
console.log('Removed bylines from blog.html');

// Fix index.html reviews
let indexHtml = fs.readFileSync('index.html', 'utf8');
indexHtml = indexHtml.replace(/name: "Sarah Jenkins",/g, 'name: "Sarah J.",');
indexHtml = indexHtml.replace(/name: "David Chen",/g, 'name: "David C.",');
indexHtml = indexHtml.replace(/name: "Maria Garcia",/g, 'name: "Maria G.",');

// Also look for names in the HTML if they are hardcoded
// Wait, the reviews are generated by JS in index.html, let's verify if there are hardcoded names elsewhere.
fs.writeFileSync('index.html', indexHtml);
console.log('Removed specific names from index.html reviews');
